export const PHRASE_BANK: readonly string[] = [
  "your ambition is just anxiety in a nicer outfit",
  "stop romanticizing chaos you created on purpose",
  "the universe is not testing you; you are stalling",
  "main character energy without the plot",
  "you call it intuition when it is just fear with good PR",
  "that soft launch of your feelings already flopped",
  "your comfort zone has a gift shop and you work there",
  "destiny is not late; you are early to excuses",
  "you keep watering a plastic plant and calling it growth",
  "the stars are not aligned; your calendar is just empty",
  "your glow-up is a costume change between identical scenes",
  "stop asking for signs while ignoring the billboard",
  "your toxic trait is treating vibes like a business plan",
  "you are not mysterious; you are inconsistent with better lighting",
  "that boundary is just a mood with a manifesto",
  "you outran responsibility and called it freedom",
  "your crush on potential is a long-term lease on disappointment",
  "the plot twist is you already knew",
  "you collect advice like souvenirs and never unpack",
  "your healing era still has the receipt for the same mistake",
  "confidence without competence is karaoke courage",
  "you are auditioning for pity and calling it vulnerability",
  "the cosmos did not ghost you; you muted yourself",
  "your standards are a museum of things you will not do",
  "stop casting others as villains in your unfinished draft",
  "you want a prophecy that agrees with last night's text",
  "your luck is rationed by how often you tell the truth",
  "you treat closure like a subscription you keep canceling",
  "the harsh truth arrives on time; your defenses are late",
  "you are not behind; you are avoiding the staircase",
  "your soft life has hard consequences waiting in the lobby",
  "stop outsourcing discernment to a mood board",
] as const;
